"""Command-line entry point for the SVM/KNN/random-forest comparison."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

from traffic_sign_system.config.settings import RANDOM_STATE, ROOT_DIR
from traffic_sign_system.evaluation.comparison import (
    load_feature_metadata,
    run_comparison,
)


def _resolve_features_path(value: Path) -> Path:
    """Accept paths relative to either the current directory or package root."""
    candidates = [value]
    if not value.is_absolute():
        candidates.append(ROOT_DIR / value)
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    searched = ", ".join(str(candidate.resolve()) for candidate in candidates)
    raise FileNotFoundError(f"Feature NPZ was not found. Searched: {searched}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train SVM/KNN/RF on one shared feature split and compare them."
    )
    parser.add_argument(
        "--features",
        type=Path,
        default=Path("models/artifacts/features_hog+hsv.npz"),
        help="Feature NPZ generated by scripts.build_features.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory (default: directory containing --features).",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=RANDOM_STATE,
        help="Random seed used for the shared stratified validation split.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    features_path = _resolve_features_path(args.features)
    out_dir = args.out_dir
    if out_dir is None:
        out_dir = features_path.parent
    elif not out_dir.is_absolute():
        # Keep explicit output paths relative to the user's current directory.
        out_dir = out_dir.resolve()

    label_map, _ = load_feature_metadata(features_path)
    df = run_comparison(
        features_path,
        out_dir=out_dir,
        label_map=label_map,
        random_state=args.random_state,
    )

    print(df.to_string(index=False))
    print(f"comparison_csv: {(out_dir / 'comparison.csv').resolve()}")
    print(f"comparison_plot: {(out_dir / 'comparison.png').resolve()}")
    print(f"confusion_matrices: {(out_dir / 'confusion_matrices.png').resolve()}")


if __name__ == "__main__":
    main()
